### ISSUE TITLE
No doors onto bridges

### ISSUE THREAD

**Issue by NthPortal** [The-Architects727/BetterEndCitiesBetterEnd#2]
There are no doors between the source tower and the bridge branching off of it, as shown in the following screenshot:

![2024-09-22_09 07 47](https://github.com/user-attachments/assets/f7cf1b52-d061-456c-b679-7b2d2ad72f41)

Doors generate fine for the buildings on the other ends of the bridges, however.

**Comment by The-Architects727** [comment]
What version are you on? So I can test the right one.

**Comment by NthPortal** [comment]
1.20.1 from modrinth (SHA256: 888ce52c30357eeb7146245e006dd630130f0386389bf07f1fb1584270c31f53)

**Comment by The-Architects727** [comment]
Is it forge or fabric version of the pack?
Also is it the datapack or mod version?
Just trying to narrow it down.

**Comment by NthPortal** [comment]
fabric. I didn't realise there was a forge version as I only saw fabric on modrinth; otherwise I would have said, sorry. I should also note that I'm using the mod version and not the datapack version

**Comment by The-Architects727** [comment]
Ok thank you. I will take a look at that today if possible.

**Comment by The-Architects727** [comment]
I have uploaded a fix to the 1.20.1 Fabric version on modrinth

**Comment by NthPortal** [comment]
massive thank you for taking care of this so quickly 💜
